Repository stefann5/graph-explorer, pull requests merged in 2025-07, with the labels that each got.

#32 Finished milestone
  README.md
  api/dist/graph_explorer_api-0.1-py3-none-any.whl
  api/dist/graph_explorer_api-0.1.tar.gz
  api/sok/graph/explorer/api/services/graph.py
  data_source_plugin_json/pyproject.toml
  data_source_plugin_json/sok/__init__.py
  data_source_plugin_json/sok/graph/__init__.py
  data_source_plugin_json/sok/graph/explorer/__init__.py
  data_source_plugin_json/sok/graph/explorer/asd.py
  data_source_plugin_json/sok/graph/explorer/data_source/__init__.py
  data_source_plugin_json/sok/graph/explorer/data_source/data_source_plugin_json.py
  data_source_plugin_json/sok/graph/explorer/data_source/main.py
  data_source_plugin_json/sok/graph/explorer/data_source/test_data.json
  data_source_plugin_xml/pyproject.toml
  data_source_plugin_xml/sok/__init__.py
  data_source_plugin_xml/sok/graph/__init__.py
  data_source_plugin_xml/sok/graph/explorer/__init__.py
  data_source_plugin_xml/sok/graph/explorer/data_source/__init__.py
  data_source_plugin_xml/sok/graph/explorer/data_source/data_source_plugin_xml.py
  data_source_plugin_xml/sok/graph/explorer/data_source/main.py
  data_source_plugin_xml/sok/graph/explorer/data_source/test.xml
  graph_explorer/db.sqlite3
  graph_explorer/graph_explorer/__init__.py
  graph_explorer/graph_explorer/settings.py
  graph_explorer/graph_explorer/urls.py
  graph_explorer/test.json
  graph_explorer/test.xml
  platform/graph_explorer_platform/__init__.py
  platform/graph_explorer_platform/admin.py
  platform/graph_explorer_platform/apps.py
  platform/graph_explorer_platform/migrations/__init__.py
  platform/graph_explorer_platform/models.py
  platform/graph_explorer_platform/search.py
  platform/graph_explorer_platform/templates/base.html
  platform/graph_explorer_platform/templates/birdview.html
  platform/graph_explorer_platform/templates/main.html
  platform/graph_explorer_platform/tests.py
  platform/graph_explorer_platform/urls.py
  platform/graph_explorer_platform/views.py
  platform/pyproject.toml
  platform/sok/graph/explorer/__init__.py
  platform/sok/graph/explorer/platform/__init__.py
  platform/sok/graph/explorer/platform/platform.py
  simple_visualizer/sok/graph/explorer/data_visualizer/simple_visualizer.py
  test_data.json
Labels: enhancement

#33 Feature/block visualizer
  block_visualizer/sok/graph/explorer/data_visualizer/block_visualizer.py
  platform/graph_explorer_platform/templates/main.html
  platform/graph_explorer_platform/templates/treeview.html
  platform/graph_explorer_platform/urls.py
  platform/graph_explorer_platform/views.py
Labels: enhancement

#35 added class diagram
  dijagram.pdf
Labels: documentation, enhancement

#37 Merging develop into Main
  block_visualizer/sok/graph/explorer/data_visualizer/block_visualizer.py
  dijagram.pdf
  platform/graph_explorer_platform/apps.py
  platform/graph_explorer_platform/models.py
  platform/graph_explorer_platform/templates/main.html
  platform/graph_explorer_platform/templates/treeview.html
  platform/graph_explorer_platform/urls.py
  platform/graph_explorer_platform/views.py
Labels: enhancement

#39 added class diagram
  dijagram.pdf
Labels: documentation
